---
title: "A talk"
description: |
  A page for a talk
author:
  - name: Nora Jones 
    url: https://example.com/norajones
    affiliation: Spacely Sprockets
    affiliation_url: https://example.com/spacelysprokets
date: "`r Sys.Date()`"
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Let's try some of John Helveston's icon link functions

```{r echo = FALSE}
source(here::here("R", "functions.R"))
```

Two calls to `icon_link` in the same code chunk puts the buttons on the same line

```{r echo = FALSE}
icon_link(
    icon = "fab fa-github",
    text = "materials",
    url  = "https://github.com/EllaKaye/ellakaye-distill"
)

icon_link(
    icon = "fab fa-github",
    text = "more materials",
    url  = "https://github.com/EllaKaye/ellakaye-distill"
)
```

Calls to `icon_link` in the different chunks put them on separate lines

```{r echo = FALSE}
icon_link(
    icon = "fab fa-github",
    text = "even more materials",
    url  = "https://github.com/EllaKaye/ellakaye-distill"
)
```

```{r echo = FALSE}
icon_link(
    icon = "fab fa-github",
    text = "materials",
    url  = "https://github.com/EllaKaye/ellakaye-distill"
)

```

Here's three in a row that fit:

```{r echo = FALSE}
icon_link(
    icon = "fab fa-github",
    text = "materials",
    url  = "https://github.com/EllaKaye/ellakaye-distill"
)

icon_link(
    icon = "fab fa-github",
    text = "materials",
    url  = "https://github.com/EllaKaye/ellakaye-distill"
)

icon_link(
    icon = "fab fa-github",
    text = "materials",
    url  = "https://github.com/EllaKaye/ellakaye-distill"
)

```

Here are three in a row that don't fit (put them on separate lines instead)

```{r echo = FALSE}
icon_link(
    icon = "fab fa-github",
    text = "lots materials",
    url  = "https://github.com/EllaKaye/ellakaye-distill"
)

icon_link(
    icon = "fab fa-github",
    text = "lots more materials",
    url  = "https://github.com/EllaKaye/ellakaye-distill"
)

icon_link(
    icon = "fab fa-github",
    text = "yet more materials",
    url  = "https://github.com/EllaKaye/ellakaye-distill"
)

```
